import Link from "next/link";

export function Footer() {
  const referenceURL =
    "https://snaped.fns.usda.gov/resources/nutrition-education-materials/seasonal-produce-guide";

  return (
    <div className="fixed bottom-0 right-0 p-2 text-xs text-right">
      <div>
        Produce data provided by{" "}
        <Link
          className="cursor-default"
          href={referenceURL}
          rel="noopener noreferrer"
          target="_blank"
        >
          USDA 🌱
        </Link>
      </div>
      <div>Descriptions generated by OpenAI 🤖</div>
    </div>
  );
}
